[pytest]
addopts =
    -v
    --alluredir=reports/allure-results
testpaths = tests
pythonpath= .
asyncio_mode = auto
log_cli = true
log_level = DEBUG
markers =
    healthcheck: Full API Healthcheck Suite
    smoke: Smoke tests (Critical happy path)